Adding exception, printing the list of availbale configurations
DUNE-DAQ/drunc pull request #127
Opened 2024-07-04 09:56 UTC by PawelPlesniak

2024-07-04 09:59 UTC, alessandrothea requested changes

2024-07-04 09:59 UTC, alessandrothea commented on src/drunc/unified_shell/shell.py
> +            raise DruncShellException(f"Configuration {os.path.splitext(process_manager_configuration)[0]} is not found in the package. The packaged configurations are {[os.path.splitext(configuratio
Just an aesthetic comment: the code executes `os.path.splitext(configuration)[0]` multiple times. It's usually better do it once and use it multiple times...

2024-07-04 12:29 UTC, PawelPlesniak commented
@alessandrothea please review

2024-07-08 16:45 UTC, alessandrothea approved these changes

2024-07-09 12:41 UTC, merged