Introducing a new Kubernetes Process Manager to drunc
DUNE-DAQ/drunc pull request #42
Opened 2024-04-29 09:40 UTC by TiagoTAlves

Made a new K8s pm:
As of now we have a working `boot`,` ps`, `kill` and `restart`.

At boot we take the `boot_request` and create a namespace, and pods that fit within this namespace. The namespace is taken from the boot command:
`boot file <configuration> <session-name/namespace>`
The UUIDs are generated in the same way as the SSHpm and given to each of the processes and also added as labels to the pods.

At ps, it takes either `uuid`, `session`, `user` or `name` of pod and shows the query as a list. If ps is left just as the ps command, then all processes will be shown.

At restart, you take the query and find the associated `boot_request`. This `boot_request` is then copied and deleted so that a new pod can be booted in its place. The uuid will stay the same because it goes through the boot command once again. The restart command works with `uuid` and `name`.

At kill, processes are killed individually regardless of the query format. If all processes within a `session` are killed, then the namespace should automatically be killed. The kill command works with `uuid`, `session`, `user` or `name` .

2024-04-29 16:00 UTC, TiagoTAlves commented
The flush has now been added too.
It checks to see if queried pods are alive, if they are not alive, then the `boot_request` is deleted. 
If the session  has no more pods in it, the `session` /namespace is also deleted

2024-05-01 11:01 UTC, plasorak requested changes
Hi Tiago, thanks for this, it looks pretty good. Few relatively minor comments.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +from functools import partial
Do you use this one anywhere?

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                return
this `return` should return something (true or false).

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                self._log.info(f"Added label \"{key}:{label}\" to pod \"{obj_name}\" in \"{namespace}\" namespace")
I'd add
```
else:
  raise DruncException(f"cannot add label to object type {obj_type}")
```

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                raise e
This is not the best way to do this.
Is there no way to list all the namespaces in the Python Kubernetes API? I'd avoid exception throwing/catching in the logic of the code. After creating it, you also need to add the creator label on the namespace.
So I'd do something like:
```python
namespaces = self._core_v1_api.list_namespace() # from https://stackoverflow.com/a/55731791
if nsname in namespaces:
    return
namespace_manifest = {
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {"name": nsname},
}
self._core_v1_api.create_namespace(namespace_manifest)
self._add_creator_label(nsname, 'namespace')
```

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +        config.load_kube_config()
remove this line, as it's in `__init__()`.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +        except:
Here, I'd be more careful and create a `DruncK8sNamespaceAlreadyExist` exception that gets thrown by `self._create_namespace` and only catch that specific one when you call that function.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                    return_code = self.boot_request[uuid].exit_code
I'm pretty sure this will not work, since you defined `self.boot_request[uuid]` to be `BootRequest`

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +            sleep(10)
Eugh, no, let's not do that. you should poll if the pod exists with `list_namespaced_pod` and `boot` after it has disappeared.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                    return_code = self.boot_request[uuid].exit_code
Ditto, `boot_request` isn't an actual process but a message containing information to start the process.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                except Exception as e:
I'd try to remove `except Exception` as much as possible everywhere, it's a bit unsafe.

2024-05-01 11:01 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                    return_code = self.boot_request[uuid].exit_code
Same, that won't work.

2024-05-01 11:19 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +from functools import partial
Deleted

2024-05-01 11:19 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                return
Added `return False`

2024-05-01 11:19 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                self._log.info(f"Added label \"{key}:{label}\" to pod \"{obj_name}\" in \"{namespace}\" namespace")
Added `DruncException`

2024-05-01 11:19 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +        config.load_kube_config()
Removed

2024-05-01 11:20 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                    return_code = self.boot_request[uuid].exit_code
Is the exit code the image exit code?

2024-05-01 11:21 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +            sleep(10)
This was just me being lazy, will make this change

2024-05-01 12:01 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                raise e
Slightly different:
`    def _create_namespace(self, nsname):
        ns_list = self._core_v1_api.list_namespace()
        ns_names = [ns.metadata.name for ns in ns_list.items]
        self._log.info(f'ns_list: {ns_names}')
        if not nsname in ns_names:
            namespace_manifest = {
                "apiVersion": "v1",
                "kind": "Namespace",
                "metadata": {"name": nsname},
            }
            self._core_v1_api.create_namespace(namespace_manifest)
            self._add_creator_label(nsname, 'namespace')
        else:
            return `

2024-05-01 13:45 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                    return_code = self.boot_request[uuid].exit_code
What I have so far, I don't know if this is what the error code wants

```python
            if self.is_alive(podname, session):
                return_code = self._core_v1_api.read_namespaced_pod_status(podname, session).status.container_statuses[0].state.terminated
            else:
                return_code = 404
```

2024-05-01 14:04 UTC, TiagoTAlves commented
@plasorak Fixed some but I feel like maybe return_code isn't quite right and might need some help

2024-05-03 14:22 UTC, plasorak requested changes

2024-05-03 14:22 UTC, plasorak commented on src/drunc/exceptions.py
> +        super().__init__(*args, **kwargs)
Can this go in a new file (?) `src/drunc/process_manager/exceptions.py`

2024-05-03 14:24 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                    self._log.error(f"Namespace \"{session}\" does not exist")
Are you sure this only happens when the namespace doesn't exist? Feels like it could also be when the pod in that namespace doesn't exist.

2024-05-03 14:27 UTC, TiagoTAlves commented on src/drunc/exceptions.py
> +        super().__init__(*args, **kwargs)
Yeah sure `k8s_exceptions.py`?

2024-05-03 14:27 UTC, plasorak commented on src/drunc/process_manager/k8s_process_manager.py
> +                except self._api_error_v1_api as e:
Please use `list_namespaced_pod` rather than catching a 404 error for unfound pod.

2024-05-03 16:23 UTC, plasorak commented
I gave it a go on the NP04 cluster.
Can you add these labels to the namespace? Otherwise, we cannot start Pod, I think. https://github.com/DUNE-DAQ/nanorc/blob/production/v4/src/nanorc/k8spm.py#L187

2024-05-04 10:39 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                    self._log.error(f"Namespace \"{session}\" does not exist")
Changed logic

2024-05-04 10:39 UTC, TiagoTAlves commented on src/drunc/process_manager/k8s_process_manager.py
> +                except self._api_error_v1_api as e:
Changed logic

2024-05-07 16:17 UTC, plasorak approved these changes
Looks good

2024-05-07 16:17 UTC, merged